name: Build, test and deploy ASP.Net Core app to Azure Web App - gifty-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Gifty.Api/Gifty.Api.csproj

      - name: Build
        run: dotnet build Gifty.Api/Gifty.Api.csproj --configuration Release

      - name: Publish
        run: dotnet publish Gifty.Api/Gifty.Api.csproj -c Release -o ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore test project dependencies
        run: dotnet restore Gifty.Tests/Gifty.Tests.csproj

      - name: Run tests
        run: dotnet test Gifty.Tests/Gifty.Tests.csproj --configuration Release --verbosity normal
        env:
          DefaultConnection: "Host=localhost;Port=5433;Database=GiftyDb;Username=postgres;Password=postgrespassword123"
          Redis: "localhost:6379"
          UseTestAuth: "true"
          ASPNETCORE_ENVIRONMENT: "Development"

  deploy:
    runs-on: windows-latest
    needs: [build, test]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A54498DC486B4443A2648410E2E66707 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_808D64E61AE54C2B876E67F9EECB8955 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7FF2A714DD2C4B1B9CF5D01029AA92F0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gifty-api'
          slot-name: 'Production'
          package: .
